Add option to deploy udp-only service
hahow/prometheus-statsd-exporter pull request #10
Opened 2021-08-19 07:01 UTC by skylt

On some cloud providers, namely AWS, it isn't currently possible to have a load-balancer handling both TCP and UDP traffic, although this will arrive in the future.

This merge request adds support for deploying a second service that will handle UDP traffic independently.

@jason2506 could you review this please ?

2021-09-01 13:26 UTC, skylt commented
@jason2506  @hahow , would it be possible for you to review this ?
Thank you

2021-09-02 02:13 UTC, jason2506 requested changes
@skyit, Sorry for not getting back to you sooner. I just reviewed the changes, but I am no longer a member of @hahow, so I am not authorized to merge this pull request.

2021-09-08 12:58 UTC, skylt commented on templates/service.yaml
> +    {{- if and (empty .Values.statsd.udpPort) (not (empty .Values.service.enable_separate_udp_service)) }}
Thank you for your review.

2021-09-08 12:59 UTC, skylt commented
Hello @amowu, @choznerol, @okischuang, @tommy60703, sorry for pinging all of you.
Could you review / merge this PR please ?

2021-09-09 01:14 UTC, amowu commented
> Hello @amowu, @choznerol, @okischuang, @tommy60703, sorry for pinging all of you.
> Could you review / merge this PR please ?

@yade-hahow @WeiAnAn

2021-09-09 11:12 UTC, WeiAnAn reviewed
Thanks for your contribution.

Could you follow the [helm naming convention](https://helm.sh/docs/chart_best_practices/values/#naming-conventions), just replace snake case to camel case in values, it will be nice!

2021-09-09 11:12 UTC, WeiAnAn commented on templates/service.yaml
> +    {{- if and (not (empty .Values.statsd.udpPort)) (not .Values.service.enable_separate_udp_service) }}
```suggestion
    {{- if and (not (empty .Values.statsd.udpPort)) (not .Values.service.enableSeparateUdpService) }}
```

2021-09-09 11:12 UTC, WeiAnAn commented on templates/service.yaml
> +{{- if .Values.service.enable_separate_udp_service }}
```suggestion
{{- if .Values.service.enableSeparateUdpService }}
```

2021-09-09 11:12 UTC, WeiAnAn commented on values.yaml
> +  enable_separate_udp_service: false
```suggestion
  enableSeparateUdpService: false
```

2021-09-15 13:24 UTC, skylt commented
Thank you for your review @WeiAnAn , the changes have been committed.

2021-09-16 02:32 UTC, WeiAnAn approved these changes

2021-09-16 02:37 UTC, merged